### ISSUE TITLE
`man apertium-tagger` outdated compared to --help

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium#10]
The man page for apertium-tagger doesn't mention e.g. `-x`. The `--help`  seems more up-to-date. They should be synced.

**Comment by nvinayvarma189** [comment]
I would like to work on this. Currently, I see `-z`, `-u`, `-w`, `-x`, `-v` missing in man page of `apertium-tagger`. A little description about them should be added to `apertium-tagger.1` right?. Also, to see it's working we need to pass respective files into the `DIC`, `CRP`, `TSX` etc, arguments. Can you help me with where can I find those suitable files?

**Comment by unhammer** [comment]
Sorry, missed your answer. What do you mean suitable files? `apertium-tagger.1` is the only file that needs changing.

**Comment by sandy9999** [comment]
Has this issue been resolved yet?

**Comment by TinoDidriksen** [comment]
I don't actually know. Compare https://github.com/apertium/apertium/blob/master/apertium/apertium-tagger.1 with what `apertium-tagger --help` and source file says should be available.

**Comment by sandy9999** [comment]
What does this file apertium-tagger-apply-new-rules.1 do?

**Comment by AdityaVi99** [comment]
can some how to resolve this issue
i wan to do my contribution

**Comment by ftyers** [comment]
@sandy9999 @AdityaVi99 please do not use GitHub issues to have a conversation. If you don't know what to do you should talk to us on IRC/Matrix, not through GitHub issues.

**Comment by AdityaVi99** [comment]
>  @AdityaVi99 please do not use GitHub issues to have a conversation. If you don't know what to do you should talk to us on IRC/Matrix, not through GitHub issues.
what is IRC/matrix I dont know...
