### ISSUE TITLE
Compiled PCRE patterns are not endian-neutral

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium#112]
This has always been broken and we never noticed. But Debian noticed: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977753 - fails to test on big-endian s390x, because of the new binary compat tests.

It's the precompiled PCRE patterns again. They're not version-safe, nor apparently endian-safe.

`bool recompile_attrs = Compression::string_read(in) != string(pcre_version());` on https://github.com/apertium/apertium/blob/master/apertium/transfer.cc#L106 - if I add in `recompile_attrs = true;` after, then it works.

**Comment by unhammer** [comment]
![s390x](https://user-images.githubusercontent.com/56868/102786798-5aac4600-43a0-11eb-81e5-4ee057a75514.jpeg)

High priority bug imo. We *need* Apertium running on one of these =D
