### ISSUE TITLE
Remove gender bias (metaissue)

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium#124]
Gender bias permeates Apertium language modules and translation pairs.  The following are some examples:
* In languages with gendered pronouns, articles, etc., the masculine form is usually used as the lemma;
* In translation from a language without gendered pronouns to one with, the masculine pronoun is usually chosen as the default translation, to the exclusion of non-gendered options (such as singular "they" in English);
* In translating from a non-gendered noun in one language to a "natural-gendered" noun in another language, the masculine member of the pair is usually selected;
* In languages where a "masculine plural" form is used to refer to mixed-gender groups (e.g., Spanish "los abuelos"), this is usually tagged as `<m><pl>` instead of `<mf><pl>`;
* Some pronouns used to refer to non-binary individuals are not included or the non-binary analyses are not among those available and are not used in translation pairs (such as English singular "they").

This likely just grazes the surface.  I'd like to use this issue as a place to gather general observations, carry out general discussion, and link to individual issues that address these problems in specific languages modules and translation pairs.

**Comment by mr-martian** [comment]
It might make more sense to move this to https://github.com/apertium/organisation

**Comment by jonorthwash** [comment]
Moved to https://github.com/apertium/organisation/issues/29.
