### ISSUE TITLE
Python bindings should link to .so

### ISSUE THREAD

**Issue by mr-martian** [apertium/apertium#128]
rather than maintaining a list of all `.cc` files in `apertium/` and recompiling all of them, it seems like it should be possible to have `python/setup.py` just link to the `.so` file that the normal compilation process produces. Or maybe all the (rather trivial) Python bindings should be in https://github.com/apertium/apertium-python or something.

**Comment by TinoDidriksen** [comment]
https://github.com/hfst/hfst/blob/master/python/setup.py does it.
