### ISSUE TITLE
"v" tag in transfer

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium#154]
It would be useful to be able to use the `v` tag in `def-cat`, `def-item`, `def-list` and `list-item`. Could it be done?

**Comment by mr-martian** [comment]
`list-item` already has a `v` attribute.

What do you want `v` to do in the other cases?

**Comment by hectoralos** [comment]
At least `def-item` would be useful. By the way, also `def-var `would help in order to be able to initialize a variable with different values, depending on the language variety.

**Comment by mr-martian** [comment]
Ah. I was thrown off by the handful of things in transfer that `v` as in "value" and you want it for "variety".

I can definitely add `cat-item` and `attr-item` to `apertium-filter-rules`. `def-var` and `list-item` are a bit trickier, given the name conflict.

**Comment by hectoralos** [comment]
True. The items are the most important, so that's OK.

**Comment by hectoralos** [comment]
Thanks!

**Comment by hectoralos** [comment]
After the night build it still does not work:
`apertium-oci-fra.fra-oci.t2x_bis`:
```
    <def-cat n="REL_que">
      <cat-item lemma="que" tags="rel" v="oci"/>
      <cat-item lemma="qui" tags="rel" v="oci@gascon"/>
    </def-cat>
```
```
$ make
apertium-filter-rules oci apertium-oci-fra.fra-oci.t2x_bis >fra-oci.t2x_bis
apertium-validate-interchunk fra-oci.t2x_bis
fra-oci.t2x_bis:296: element cat-item: validity error : No declaration for attribute v of element cat-item
Document fra-oci.t2x_bis does not validate against /usr/share/apertium/interchunk.dtd
make: *** [Makefile:1037: fra-oci.t2x_bis.bin] Error 3
```
`fra-oci.t2x_bis`:
```
    <def-cat n="REL_que">
      <cat-item lemma="que" tags="rel" v="oci"/>

    </def-cat>
```

**Comment by mr-martian** [comment]
fixed now - totally forgot about the validator.
