### ISSUE TITLE
apertium-filter-rules creates invalid T1X file

### ISSUE THREAD

**Issue by MarcRiera** [apertium/apertium#155]
When `apertium-filter-rules` is used on a T1X file from a pair without chunking, the resulting file is invalid and doesn't compile. This seems a side effect of 552a9d6d6a624db58a1a1295b6612a6cd26c01fa, specifically here: https://github.com/apertium/apertium/blob/552a9d6d6a624db58a1a1295b6612a6cd26c01fa/scripts/filter-rules.xslt#L62

On pairs with chunking, `default="chunk"` is specified to output chunks. Specifying no attribute is valid and equals to `default="lu"`, which allows outputting lexical units (in pairs with 1-step transfer). The template creates `default=""` in this case, which is invalid.

The `default` attribute should be present in the resulting T1X file only if it existed in the input file.

**Comment by mr-martian** [comment]
I believe if the template for `<transfer>` is deleted and `transfer` is added to the list currently on line 96 it should fix this issue (I'm not on a device where I can test this at the moment).

**Comment by MarcRiera** [comment]
It didn't work, but I solved it by limiting the existing template to `<transfer>` only when it includes `default` and adding a new template without the attribute. This way, the first template is skipped if there's no attribute.
