### ISSUE TITLE
apertium accesses the network during build

### ISSUE THREAD

**Issue by bentley** [apertium/apertium#16]
Creating apertium-gen-deformat script
    Creating apertium-gen-reformat script
    Creating apertium-validate-tagger script
    Creating apertium-validate-transfer script
    Creating apertium-validate-dictionary script
    Creating apertium-validate-modes script
    Creating apertium-validate-interchunk script
    Creating apertium-validate-postchunk script
    Creating apertium script
    Creating apertium-unformat script
    Creating apertium-validate-acx script
    Creating apertium-utils-fixlatex script
    svn checkout https://github.com/unhammer/apertium-get/trunk apertium-get
    svn: E170013: Unable to connect to a repository at URL 'https://github.com/unhammer/apertium-get/trunk'
    svn: E670005: no address associated with name

On OpenBSD we build packages as an unprivileged user with no network access. If this script is required to build then it should be included in the source tarballs…

**Comment by ftyers** [comment]
@bentley  agree, I think this is perhaps something that @unhammer  could fix ?

**Comment by TinoDidriksen** [comment]
This is simply because the release tarballs were created automatically and thus incorrectly. This was discussed on the -stuff mailing list ages ago.

**Comment by unhammer** [comment]
So the quick fix is to put that subfolder into the tarball.

But maybe we should put the apertium-get repo into apertium?

**Comment by sushain97** [comment]
Feel free to transfer it! I think you can?

**Comment by ftyers** [comment]
@unhammer yes, let's transfer it. :)

**Comment by unhammer** [comment]
Oh it's under my user even, transferred ownership.

But what I actually meant was: Should we just make it a real subfolder of this repo? Seems a bit more KISS.

**Comment by sushain97** [comment]
I'm fine with subdirectory or submodule if we want it to be discrete with its own issues, etc. The latter has more overhead but it does seem more logically sound.

**Comment by unhammer** [comment]
Hm, as `apertium-get` is mostly meant for developers / bleeding edge users, keeping it separate but recommended might make sense.
