### ISSUE TITLE
Bug in docx output?

### ISSUE THREAD

**Issue by fjohansen** [apertium/apertium#169]
I have recently got an error translating docx files from norwegian bokmål to nynorsk. Sometimes the translation works just fine, but I have a document which always results in a corrupt file after translation. There's no error from the apertium script.

After spending some time trying to figure out what causes it, I found a sentence that will always produce a corrupt docx. 

How to reproduce: 
Create a Word file with this sentence:
`Både i form av for få ansatte på jobb, og mye overtid.`
Run it through apertium with 
`-f docx nob-nno_e /path_to_input.docx output.docx`

If you remove the comma in the above sentence in the input docx, apertium creates a perfectly ok file.

FYI: The corrupt output file can be viewed in MacOS's quick look feature even if Microsoft Word is not able to open it.

**Comment by unhammer** [comment]
Kan du lasta opp eit slikt dokument med den eine setninga her?

**Comment by fjohansen** [comment]
[Doc4.docx](https://github.com/apertium/apertium/files/8987215/Doc4.docx)

Hei. Vedlagt finner du en fil som gir feil hos meg.

**Comment by unhammer** [comment]
Tusen takk for fil og feilrapport :) Eg er ganske sikker på dette er ein kjend feil. Ein fiks er på veg, men det kan nok ta over sommaren før alt er testa og klart. Eg lukkar denne, klikk subscribe på [lttoolbox#145](https://github.com/apertium/lttoolbox/issues/145) om du vil ha varsel om når det er retta.
