### ISSUE TITLE
Include distfiles as release assets

### ISSUE THREAD

**Issue by bentley** [apertium/apertium#18]
The [Apertium releases](https://github.com/apertium/apertium/releases) don’t currently include any release tarballs generated by make dist; they only contain the default tarballs generated by GitHub.

These aren’t suitable for packaging:

* GitHub’s autogenerated tarballs are not stable—they’re subject to change when GitHub’s infrastructure changes (e.g., their backends update git/gzip/tar…), breaking packaging systems that assume the tarball has a consistent checksum
* They require the user/packager to depend on Autoconf and Automake

Once generated with `make dist`, distfiles can be easily attached to a tag on the GitHub releases page.

I’ve attached a copy of [apertium-3.5.1.tar.gz](https://github.com/apertium/apertium/files/2079209/apertium-3.5.1.tar.gz) which I generated with `make dist`. The 3.5.0 tag could use the distfile [already uploaded to SourceForge](https://sourceforge.net/projects/apertium/files/apertium/3.5/apertium-3.5.0.tar.gz/download). I’d be willing to upload these myself, but I don’t seem to have the permissions for that.

**Comment by TinoDidriksen** [comment]
Next releases will all be the way you want, as discussed on the mailing list a few months ago. There just haven't been any releases since then. Because of the lttoolbox fixes, I'll make new releases of all the core tools when I am back in Denmark and awake, probably tomorrow.
