### ISSUE TITLE
Capitalization restoration does not remove internal marks

### ISSUE THREAD

**Issue by MarcRiera** [apertium/apertium#183]
I have tried the new capitalization processing/restoration modules with `apertium-eng-cat` and it looks very interesting, because it solves generation errors with many lemmas: https://github.com/apertium/apertium-eng-cat/tree/caps

However, I have found that capitalization restoration does not remove internal marks in blanks, which makes translation unusable at least when using the pipeline without a deformatter/reformatter (tested on commandline and Apertium Viewer). Here is an example from the commandline:
```
$ echo "house" | apertium -d . eng-cat
c:aa/aacasa/c:aa/aa./
```
Expected result:
```
$ echo "house" | apertium -d . eng-cat
casa
```
Thanks!

**Comment by mr-martian** [comment]
In some sense this is a more general issue with the relationships between the format-handlers and wblanks, but it's fairly easy to strip out the wblanks, so I'll just do that and wait for the old format handlers to become deprecated.
