### ISSUE TITLE
modes files should allow aliases

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium#2]
There should be a way to specify aliases in modes files. Probably about 25% of the time I find myself typing e.g. `grn-spa-transfer` instead of `grn-spa-chunker`, or `grn-spa-generador` instead of `grn-spa-dgen`. It would be cool to be able to alias the most popular/common ones.

**Comment by unhammer** [comment]
I think this should be easy to do with the "gendebug" feature, requiring some change to https://github.com/apertium/apertium/blob/master/apertium/modes2debugmodes.xsl

The template for "program" already generates some variants for every program:
https://github.com/apertium/apertium/blob/master/apertium/modes2debugmodes.xsl#L135

**Comment by mr-martian** [comment]
#68 probably closes this
