### ISSUE TITLE
c:AA/Aa given to "Distrikts-NRK"

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium#204]
I was trying out this rule
```
        <!-- Keep shouting as-is: -->
        <rule weight="6.0">
            <match srcsurf="AA" select="AA"/>
        </rule>
```
but it matched inputs which contain lower letters:
```
$ echo Distrikts-NRK|\apertium -d . nob-nno_e-decase
c:AA/Aa^Distrikts-<np><guess><cmp><guio>+NRK<np><org><Aa><@app>$c:aa/aa^.<sent><clb><aa><@s-gr>$

$ echo NTB-Ritzau-TT|\apertium -d . nob-nno_e-decase
c:AA/AA^NTB<np><org><cmp>+Ritzau<np><org><cmp>+TT<np><org><Aa><@app>$c:aa/aa^.<sent><clb><aa><@s-gr>$
```
@mr-martian  is there a way to match only those which have at least one upper-case letter and no lower-case ones?

**Comment by mr-martian** [comment]
Is that the input or the output of the -restore-caps?

**Comment by unhammer** [comment]
```
$ echo NTB-Ritzau-TT|\apertium -d . nob-nno_e-recase
NTB-RITZAU-TT
```

**Comment by unhammer** [comment]
decase was extract-caps, recase restore-caps

**Comment by mr-martian** [comment]
-extract-caps reduces to a 2-letter code by copying the logic that was used everywhere else of looking at the first letter and the last letter. What you could do in this case is check both the source surface caps and the dictionary caps at once.

**Comment by unhammer** [comment]
As in `<match srcsurf="AA" srclem="aa" select="AA"/>`? That'll keep `STOR` (lemma `stor`) upper, and not uppercase `NTB-Ritzau-TT`, but it'll also uppercase `StoR`. If a new organization or whatever pops up that's named `StoR`, I don't want to turn it into `STOR` (such things happen more often than you'd think).

@ftyers  Is there any linguistic reason why `AA` in the rest of apertium only looks at first and last letter, or was this perhaps just an optimisation/shortcut?

**Comment by mr-martian** [comment]
`srclem="*aA*" select="dix"` as a high-weighted rule is probably desirable in most rulesets (I suppose this is hypothesizing that anything with weird source case is probably proper and thus will have case specified in the target).

**Comment by unhammer** [comment]
I was talking about the case where there's an unknown (not in dix) organization (or product name or whatever) that shows up, in that case we want to keep capitalisation even if it's ambiguous with some all-lowercase dix entry like `^StoR/stor<adj><sint><pst><mf><sg><ind>$`

**Comment by mr-martian** [comment]
I suppose instead of or in addition to a two-letter representation of case, we could also just put the whole original form in the wblanks to be manipulated.

**Comment by unhammer** [comment]
Might be handy, but I'm not sure it's necessary. Would it solve the problem with `srcsurf=AA` matching stuff that doesn't equal the output of `select=AA`?

**Comment by mr-martian** [comment]
yes, because `AA` wouldn't match a string with a lowercase letter in the middle

**Comment by unhammer** [comment]
OK, I was not thinking very clearly; if the tagger output was like `stor<adj>` , then it might well get translated to `big<adj>` and it doesn't make sense to keep capitalisation; the tagger would have to add an analysis like `StoR<np><cgguess>`  in which case we can just use `select=dix` in crx, e.g.

```xml
        <!-- Keep funnily spelled words funnily spelled: -->
        <rule weight="10.0">
            <match srclem="*aA*" select="dix"/>
        </rule>

        <!-- Keep shouting as-is, but only if srclem was lower: -->
        <rule weight="6.0">
            <match srcsurf="AA" srclem="aa" select="AA"/>
        </rule>
```

**Comment by unhammer** [comment]
fixed in https://github.com/apertium/apertium/commit/aa451bbd4f141f4e5a6415d8178e064b64ef28a4 :

```
$ echo 'Distrikts-NRK'|apertium -f none -d . nob-nno_e-decase
[[c:AA/AA]]^Distrikts-<np><guess><cmp><guio>+NRK<np><org><Aa><@subj>$
```
