### ISSUE TITLE
Apertium-deshtml encoding problems when html entities are present

### ISSUE THREAD

**Issue by mfl1979** [apertium/apertium#212]
Hi,

we are encountering this behaviour only with RedHat (Apertium 3.8.3), so it's probably something related to this Linux distribution, but maybe some of you have found this problem before and can shed some light on where it may come from:

When no html entities are given to the deformatter, it works as expected:

```
$ echo "España" | apertium-deshtml
España.[][
]
```

But, if the input text is html encoded:

```
$ echo "Espa&ntilde;a" | apertium-deshtml
Espaￃﾱa.[][
]
```
![image](https://github.com/user-attachments/assets/d4512e41-85f4-4e0e-8f1c-be7a70722845)

Locale is UTF-8. Any ideas?

Thanks in advance.

**Comment by TinoDidriksen** [comment]
Which exact RedHat? And where did you install Apertium from (source, packages, etc)?

**Comment by mfl1979** [comment]
Hi, it's RH 8.6.
```
 cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
```
 And Apertium 3.8.3 and lt-toolbox 3.7.1 were installed from sources published here:

```
https://github.com/apertium/apertium/archive/refs/tags/v3.8.3.tar.gz
https://github.com/apertium/lttoolbox/archive/refs/tags/v3.7.1.tar.gz
```

Thanks

**Comment by TinoDidriksen** [comment]
I can confirm the behavior you're seeing. Those versions produce that output.

However, using latest versions of lttoolbox and apertium works correctly, even on RHEL 8, so it's been solved at some point in the interim. I can't quite see what commit that would be at a quick glance, though.
