### ISSUE TITLE
unclosed superblank will leak memory

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium#213]
`echo '[' | apertium-transfer -b apertium-myv-mdf.myv-mdf.t1x myv-mdf.t1x.bin
`
will eat ram real quick. Probably shouldn't. (Seems to happen regardless of t1x file, also t2x)

**Comment by mr-martian** [comment]
https://github.com/apertium/apertium/blob/04ac90c6d8268867f60ccb32b478e1a596b0b24e/apertium/transfer.cc#L844-L868

**Comment by unhammer** [comment]
just needs a break on U_EOF?

**Comment by mr-martian** [comment]
I'd also break on \0, but yeah.
