### ISSUE TITLE
t?x let element shoudl warn if it loses stuff

### ISSUE THREAD

**Issue by flammie** [apertium/apertium#23]
I tend to think the let element in t?x scripting language as let of any programming language and commonly confused when code like:

```xml
<let><clip pos="1" part="case" side="tl"/><lit-tag v="nom"/></let>
...
<lu>
<clip part="lem" pos="1" side="tl"/>
...
<clip part="case" pos="1" side="tl"/>
...
```

will create an empty string for the case part. Because there is nothing matching the case attr in source langauge. If it were possible to detect this on runtime and warn it would help my debugging times a lot, I think I must've spend days debugging this counting all instances tgether ;-D

**Comment by unhammer** [comment]
Maybe do it when `-t` is on? Sounds useful

**Comment by mr-martian** [comment]
I believe #62 closes this.

**Comment by unhammer** [comment]
Maybe we can leave it open until we have a regression test?
