### ISSUE TITLE
lrx-proc treats "*" differently from transfer (requires a star per tag)

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium#27]
In the lrx format, I have to specify exact amount of tags, whereas in transfer, "*" can skip many tags. E.g.

I need this in lrx:
```
<match tags="n.*.*.*.cmp"/>
```
while in transfer I can just do:
```
<match tags="n.*.cmp"/>
```

**Comment by TinoDidriksen** [comment]
Belongs in https://github.com/apertium/apertium-lex-tools ?

**Comment by unhammer** [comment]
wops, keep forgetting that
