### ISSUE TITLE
use just xmllint instead of $XMLLINT in Makefile.am / generated scripts

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium#28]
Scripts like apertium-validate-dictionary refer to the xmllint that configure finds at the time you ran it, e.g. `/opt/local/bin/xmllint`. That makes the script not work if you copy it to other computers or install xmllint to a different path. Let it just use `xmllint` with no path.

(similarly for bash – some systems might use `sh` there, which is even worse, since `sh` on some systems is definitely not bash-compatible)

**Comment by b-thebest** [comment]
Can I work on this issue?

**Comment by TinoDidriksen** [comment]
@b-thebest, yes, and you don't have to ask. Just submit a PR that fixes the issue.
