### ISSUE TITLE
reject-current-rule in interchunk/postchunk too

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium#34]
I have a rule that changes tl determiner gender to fit the following noun gender, but I'd not like it to apply if the source language genders don't match up (meaning they shouldn't be chunked). In t1x/chunker, I can use `<reject-current-rule shifting="no">` to undo the two-word rule match and go back to the single-word rules, but that's not implemented yet for interchunk, where I have to duplicate the contents of the single-word rules inside the two-word rules, which is not very [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

@jimregan is there any reason it would be harder to do in interchunk than in chunker?

**Comment by jimregan** [comment]
Shouldn't be much difference, just didn't have a use case for interchunk
