### ISSUE TITLE
Document "tags" in transfer/interchunk/postchunk.dtd

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium#38]
> The part attribute in clip tag has strange value of "tags" , which is
> not one of the 4 literals in the documentation and not in def-attrs.
>
> clip pos="1" side="tl" part="tags"

https://sourceforge.net/p/apertium/mailman/message/36596119/

This should go in the docs

**Comment by aboelhamd** [comment]
Hi, unhammer. could I request an account in the wiki ?
I was following apertium2 documentation while implementing the chunker and it said that attribute part could take only 4 literals (lem, lemh, lemq or whole) that's beside one of the def-attrs. It was solved then, but from where could one know what part to update, is there any other up-to-date documentation 
 or I shall discover it by trial and error and then asking ? Also I remember that I needed to add a new attribute "id" to the transfer rules , is this too needed to be added to documentation ?
And by docs, you mean the wiki or what ?

**Comment by unhammer** [comment]
In this case, by docs I meant the dtd. The dtd doesn't mention that the attribute `part` can have the special value `tags`. The transfer files are validated against the dtd's on compile, so the stuff that a dtd can catch is at least going to be up-to-date, but they also tend to have some useful comments.

Regarding the apertium2 pdf documentation,  see https://github.com/apertium/apertium/pull/40 for the new and improved version – @IlnarSelimcan did you make a new Issue or PR, now that #40  is closed?

Regarding Wiki: What username would you like? And what e-mail should the password go to? The wiki's nice for putting project proposals on, and various tips and tricks, but it's not ideal for "official documentation".

**Comment by IlnarSelimcan** [comment]
> Regarding the apertium2 pdf documentation, see #40 for the new and improved version – @IlnarSelimcan did you make a new Issue or PR, now that #40 is closed?

Hi! No, not yet.

**Comment by aboelhamd** [comment]
wiki account : username = "aboelhamd" and email = "aboelhamd.abotreka@gmail.com"

**Comment by aboelhamd** [comment]
@unhammer , I took a look at transfer.dtd and I didn't find a thing to change except for the comment.
Is that all ?
![image](https://user-images.githubusercontent.com/20603431/54442033-8ff52000-4746-11e9-8628-c92acef815d2.png)

Also I found that id attribute is added to rule already.

**Comment by unhammer** [comment]
@aboelhamd check your inbox or spam folder for wiki registration e-mail

I see `whole` also uses the term "lexical form", but I think that should be "lexical unit" – "lexical form" sounds a bit confusing to me since the term "form" is usually about the inflected/surface form (e.g. `goes`, where `go` is the lemma and `<vblex><pres><p3><sg>` would be the tags). Could you change both to use "lexical unit", and make  a pull request?

**Comment by aboelhamd** [comment]
Thanks @unhammer for the wiki account.
I modified the three files also "lexical unit", though I found earlier in apertium2 doc that "form" was used with both surface and lexical.

**Comment by unhammer** [comment]
great! thanks
