### ISSUE TITLE
Failing to build apertium in apertium_deshtml.cc on Mac

### ISSUE THREAD

**Issue by pj1527** [apertium/apertium#42]
apertium_deshtml.cc:3963:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register yy_state_type yy_current_state;
        ^~~~~~~~~
apertium_deshtml.cc:3964:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp, *yy_bp;
        ^~~~~~~~~
apertium_deshtml.cc:3964:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp, *yy_bp;
        ^~~~~~~~~
apertium_deshtml.cc:3965:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int yy_act;
        ^~~~~~~~~
apertium_deshtml.cc:4518:6: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
        ^~~~~~~~~
apertium_deshtml.cc:4519:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *source = (yytext_ptr);
        ^~~~~~~~~
apertium_deshtml.cc:4520:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int number_to_move, i;
        ^~~~~~~~~
apertium_deshtml.cc:4520:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int number_to_move, i;
        ^~~~~~~~~
apertium_deshtml.cc:4652:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register yy_state_type yy_current_state;
        ^~~~~~~~~
apertium_deshtml.cc:4653:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp;
        ^~~~~~~~~
apertium_deshtml.cc:4677:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register int yy_is_jam;
        ^~~~~~~~~
apertium_deshtml.cc:4678:6: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register char *yy_cp = (yy_c_buf_p);

**Comment by TinoDidriksen** [comment]
Works fine if you use newer versions of Bison/Flex.

The nightly builds ( https://apertium.projectjj.com/osx/ ) are done with all dependencies installed from MacPorts ( https://macports.org/ ) and some envvars ( https://github.com/apertium/apertium-packaging/blob/master/rebuild-mac.pl#L38 ).
