### ISSUE TITLE
Apertium loses track of STDIN when called from Node.js?

### ISSUE THREAD

**Issue by oterhals** [apertium/apertium#46]
I have a peculiar issue with Apertium when called from a Node.js on Linux. It does not behave this way on macos. Consider the following Node.js code:

**File: translate.js**
```
console.log(require('child_process').execSync('/usr/local/bin/apertium -d /usr/local/share/apertium nob-nno_e', { input: 'Jeg er en pike på syv år.' }).toString());
```

The script opens a child process and runs Apertium. The input element is a string that's passed to the command through a pipe. Similar to `echo "input-string" | apertium ...`.

Excepted output here would be something like `Eg er ei jente på sju år`. But the actual output is this:

```
USAGE: /usr/local/bin/apertium-destxt [ -h | -o | -i | -n ] [input_file [output_file]]
txt format processor 
```

It seems to me as if Apertium loses track of STDIN when it tries to opens yet another subprocess.

I can get this to work if I use a workaround: wrap the call to apertium in a shell script and everything works as expected.  I.e.

**File: wrapper.sh**
```
#!/bin/bash
cat <&0 | /usr/local/bin/apertium -d /usr/local/share/apertium nob-nno_e
```

**File: translate.js** modified to this:

```
console.log(require('child_process').execSync('wrapper.sh', { input: 'Jeg er en pike på syv år.' }).toString());
```

I've noted this behavior on Google Compute Engine's Debian instances as well as in Docker containers. I would guess this is an issue that's not very common, but I thought I'd leave it here in case anyone stumbled upon a similar issue.

**Comment by TinoDidriksen** [comment]
Probably. The `apertium` wrapper script has many issues, and is not designed for instrumenting.

The way we instrument an Apertium pipe is via something like https://github.com/apertium/apertium-simpleton/blob/master/src/simpleton.cpp#L66 or https://github.com/apertium/apertium-omegat-native/blob/master/src/com/tinodidriksen/omegat/apertiumnative/ApertiumNative.java#L210 - that is, we directly do the job that the `apertium` helper does.
