### ISSUE TITLE
Space lost in cg-proc

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium#65]
I'm experimenting with CG's command [MergeCohorts](https://visl.sdu.dk/cg3/single/#mergecohorts). It absolutely suits for my needs, but the blank after the merged cohorts is lost.

This is what is happening:
Step 1:
```
$ echo "Saint-Jean a" | lt-proc -w '/home/hector/apertium/apertium-fra/fra.automorf.bin'
^Saint/saint<adj><m><sg>/saint<n><m><sg>$-^Jean/jean<n><m><sg>/Jean<np><ant><m><sg>$ ^a/avoir<vbhaver><pri><p3><sg>/avoir<vblex><pri><p3><sg>$
```
(There is a space before "$a/avoir...", like in the input)

Step 2:
```
$ echo "Saint-Jean a" | lt-proc -w '/home/hector/apertium/apertium-fra/fra.automorf.bin' | cg-proc -w '/home/hector/apertium/apertium-fra/fra.rlx.bin'
^Saint-Jean/*Saint-Jean$^a/avoir<vbhaver><pri><p3><sg>/avoir<vblex><pri><p3><sg>$
```
(The space has been lost)

So:
```
$ echo "Saint-Jean a" | lt-proc -w '/home/hector/apertium/apertium-fra/fra.automorf.bin' > output1.txt 
$ cat output1.txt | cg-proc -w '/home/hector/apertium/apertium-fra/fra.rlx.bin'
^Saint-Jean/*Saint-Jean$^a/avoir<vbhaver><pri><p3><sg>/avoir<vblex><pri><p3><sg>$
```

I attach a minimal rlx file to compile and output1.txt.
[output1.txt](https://github.com/apertium/apertium/files/4208708/output1.txt)
[apertium-fra.fra.rlx.txt](https://github.com/apertium/apertium/files/4208711/apertium-fra.fra.rlx.txt)

**Comment by TinoDidriksen** [comment]
Belongs over at https://github.com/TinoDidriksen/cg3/issues/57
