### ISSUE TITLE
cg-proc and vislcg3 do not give the same matches

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium#66]
As in #65, I have an issue using the MergeCohorts statement.

For such thing as "Saint-de-Jour" everything works fine:

```
$ echo "Saint-de-Jour" | lt-proc -w '/home/hector/apertium/apertium-fra/fra.automorf.bin' | cg-proc -w '/home/hector/apertium/apertium-fra/fra.rlx.bin'
^Saint-de-Jour/*Saint-de-Jour
```

But there are problems when there are subreadings:

```
$ echo "Saint-du-Jour" | lt-proc -w '/home/hector/apertium/apertium-fra/fra.automorf.bin' | cg-proc -w '/home/hector/apertium/apertium-fra/fra.rlx.bin'
^Saint/Saint<adj><m><sg>/Saint<n><m><sg>$-^du/de<pr>+le<det><def><m><sg>$-^Jour/Jour<n><m><sg>$
```

But, when using vislcg3, everything seems fine:

```
$ echo "Saint-du-Jour" | lt-proc -w '/home/hector/apertium/apertium-fra/fra.automorf.bin' | cg-conv -a -l | vislcg3 --trace -g '/home/hector/apertium/apertium-fra/apertium-fra.fra.rlx'
; "<Saint>"
;	"saint" adj m sg MERGECOHORTS:8
;	"saint" n m sg MERGECOHORTS:8
-
"<Saint-du-Jour>"
	"*Saint-du-Jour" MERGECOHORTS:8
; "<du>"
;	"de" pr MERGECOHORTS:8
;		"le" det def m sg
-
; "<Jour>"
;	"jour" n m sg MERGECOHORTS:8
```

I attach output1.txt, which is the output of:
`echo "Saint-du-Jour" | lt-proc -w '/home/hector/apertium/apertium-fra/fra.automorf.bin'`
And a minimal rlx file.
[output1.txt](https://github.com/apertium/apertium/files/4208820/output1.txt)
[apertium-fra.fra.rlx.txt](https://github.com/apertium/apertium/files/4208821/apertium-fra.fra.rlx.txt)

**Comment by TinoDidriksen** [comment]
Firstly, please keep CG-3 bugs to the https://github.com/TinoDidriksen/cg3 repository.

There were indeed 2 bugs in CG-3 shown by this example.

The first was that sub-readings didn't know about their wordform, so `"<(.+)>r"` didn't match them. Fixing that closes this issue.

The second issue was that non-CG text of the removed readings was not output, so the `-` were lost. Unintentionally, this is actually what you wanted in this case, but it is a bug. Non-CG text must be output, even when the owning cohorts are removed. The correct solution is that all punctuation should be analyzed and have their own cohorts and readings.

**Comment by ftyers** [comment]
@jonorthwash what do you think about doing this kind of thing in separable? Do you know what separable does with unknowns at the moment?
