### ISSUE TITLE
Port apertium-adapt-docx to ODT

### ISSUE THREAD

**Issue by xavivars** [apertium/apertium#69]
https://github.com/apertium/apertium/pull/47/files brings much better docx handling, allowing for better translations to be done.

Currently, same type of problems happen with ODT files, where formatting boundaries are incorrectly identified as word boundaries, making translations much worse than they could be.

It would be great to have a tool `apertium-adapt-odt` similar to `apertium-adapt-docx`.

**Comment by TinoDidriksen** [comment]
A bunch of this would go away if we get http://wiki.apertium.org/wiki/Reordering_superblanks + http://wiki.apertium.org/wiki/Ideas_for_Google_Summer_of_Code/Automatic_blank_handling handled.

**Comment by xavivars** [comment]
Yeah, definitely... But it's probably easier, in the short term, to have a similar workaround
