### ISSUE TITLE
Make a program or add functionality to compress spaces

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium#77]
There is absolutely no reason we should be outputting words with many spaces in:
```
Este  muy  estuvo feliz   llegó el *uchim *chajital por el *laj  *Paʼtz.   Volvieron  con el animal con placer.
```

**Comment by flammie** [comment]
add tr -s ' ' to modes?

**Comment by ftyers** [comment]
Does `tr` support null flush ? :D

**Comment by flammie** [comment]
Oh I have never had use for null flush so I wouldn't know. It probably passes the nulls through unchanged, I can't imagine there will be any complex processing in tr.

**Comment by unhammer** [comment]
"complex" doesn't have to be more than simple io buffering. This buffer needs to be flushed on NUL, otherwise it'll hang. But you could always try it and see :)

**Comment by flammie** [comment]
I made a program:
https://gist.github.com/flammie/557378ef02dfd651954f5673e608bbe4

**Comment by ftyers** [comment]
I added it in 0c2548a. It should ideally be fixed to respect (e.g. ignore double spaces) in superblanks, but otherwise, nice job!

**Comment by xavivars** [comment]
Well.... I don't think the copyright of the new file should be _2005, Universitat d'Alacant_... given that the original one had 

>  * (c) 2020 flammie@iki.fi, WTFPL

I think at least I would keep that....

**Comment by ftyers** [comment]
@flammie are you willing to assign copyright to those codes?

**Comment by flammie** [comment]
IANAL but I think the terms of wtfpl allow for such relicencing without explicit permission :-)

tbh I don't consider such c oneliner to be copyrightable on basis of it being trivial as well.

**Comment by jonorthwash** [comment]
> Oh I have never had use for null flush so I wouldn't know. It probably passes the nulls through unchanged, I can't imagine there will be any complex processing in tr.

Null flush is used by APy; otherwise things hang.

**Comment by xavivars** [comment]
Not all modules support null-flush, and Apy handles that, knowing what are the modules that do, and what are the ones that needs to instantiate for every stream in the pipeline

https://github.com/apertium/apertium-apy/blob/master/apertium_apy/utils/translation.py#L119

**Comment by unhammer** [comment]
> Not all modules support null-flush, and Apy handles that, knowing what are the modules that do, and what are the ones that needs to instantiate for every stream in the pipeline

https://github.com/apertium/apertium-apy/blob/master/apertium_apy/utils/translation.py#L119 is just about what programs need the `-z` argument. E.g. hfst-tokenize ignores -z, always flushing on NUL.

Apy also has/had code to not keep pipelines open (restart on each request instead) if they contain buggy NUL flush implementations … but no wrapper code can implement NUL flushing in a program that doesn't do it itself.

**Comment by xavivars** [comment]
That explains why some tests I tried to do do not in the past didn't work... I was completely wrong on this....

Thanks @unhammer!

**Comment by ftyers** [comment]
I'm going to close this issue now as the program exists, `apertium-posttransfer`, thanks @flammie . Future work can be getting it to process blanks properly.

**Comment by jonorthwash** [comment]
Where is that program?  Can we file an issue on its tracker?
