### ISSUE TITLE
Apertium eu-es loses line breaks with @ followed by capital letter

### ISSUE THREAD

**Issue by jelmervdl** [apertium/apertium#82]
I'm trying to translate Basque to Spanish line by line, but some combinations of characters cause lines to be collapsed into one.

I've reduced it to the following two lines:
```
words words words@words
Hau dokumentazioa
```
This becomes:
```
words words Esta words@words. la documentación
```
If I either remove the @ in the first line or the capital in the second, I do get two lines.

Script through which I pipe this text:
```
apertium-destxt -i \
| lt-proc $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/eu-es.automorf.bin' \
| apertium-tagger -g $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/eu-es.prob' \
| apertium-pretransfer \
| apertium-transfer -n $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/apertium-eu-es.ordinals.t1x'  $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/eu-es.ordinals.t1x.bin' \
| apertium-transfer $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/apertium-eu-es.eu-es.t1x'  $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/eu-es.t1x.bin'  $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/eu-es.autobil.bin' \
| apertium-interchunk $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/apertium-eu-es.eu-es.t2x'  $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/eu-es.t2x.bin' \
| apertium-postchunk $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/apertium-eu-es.eu-es.t3x'  $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/eu-es.t3x.bin' \
| lt-proc -n $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/eu-es.autogen.bin' \
| lt-proc -p $APERTIUM_PREFIX'/share/apertium/apertium-eu-es/eu-es.autopgen.bin' \
| apertium-retxt
echo ${PIPESTATUS[@]}
```

This is more or less exactly the contents of eu-es.mode. I tried removing steps to see whether I can identify which step introduces the newline but I have trouble interpreting the intermediate results, and I was not able to identify which one it is.

**Comment by ftyers** [comment]
#76 is related.

**Comment by ftyers** [comment]
@jelmervdl The formatting stuff has recently been changed by @khannatanmai and @TinoDidriksen, can you confirm that this is still an issue?

**Comment by TinoDidriksen** [comment]
Still happens. It is `apertium-transfer 'apertium-eu-es.eu-es.t1x'  'eu-es.t1x.bin'  'eu-es.autobil.bin'` that does it.

It gets input
````
^*words$ ^*words$ ^words\@words.<num>$[][
]^Hau<det><dem><sg>$ ^dokumentazio<n>$ ^a<det><art><sg>$^.<sent>$[][

]
````
and outputs
````
^unknown<unknown>{^*words$}$ ^unknown<unknown>{^*words$}$ ^D_num<SN><dem><f><sg>{^Este<det><2><3><4>$[][
]^words\@words.<num>$}$ ^det_nom<SN><art><f><sg>{^el<det><2><f><sg>$ ^documentación<n><f><sg>$}$^punt<sent>{^.<sent>$}$[][

]
````

From what I can see, it's rule https://github.com/apertium/apertium-eu-es/blob/master/apertium-eu-es.eu-es.t1x#L11968 that swaps `<num>` with `<det>`. Without the `@` then it is not `<num>`.

So there is no bug. Everything is behaving according to the written rules.

**Comment by khannatanmai** [comment]
If input is:
```
^*words$ ^*words$ ^words\@words.<num>$[][
]^Hau<det><dem><sg>$ ^dokumentazio<n>$ ^a<det><art><sg>$^.<sent>$[][

]
```
and output is:

```
^unknown<unknown>{^*words$}$ ^unknown<unknown>{^*words$}$ ^D_num<SN><dem><f><sg>{^Este<det><2><3><4>$[][
]^words\@words.<num>$}$ ^det_nom<SN><art><f><sg>{^el<det><2><f><sg>$ ^documentación<n><f><sg>$}$^punt<sent>{^.<sent>$}$[][

]
```

Then why do you say it "still happens"? It's working now right? Since the rule has a ``<b/>`` and not a ``<b pos="1"/>``, earlier it would have replaced the line break with a space but now it shouldn't, and it isn't. So it should be fixed now.

**Comment by TinoDidriksen** [comment]
Right, it's fixed, but overall behavior is undesired. That doesn't make it a bug, though. The rules behave exactly as they should, which swaps two words, which happen to have a `\n` between them.

**Comment by khannatanmai** [comment]
I think the initial issue was losing the line break and since that's fixed now it should be enough to close this particular one. @jelmervdl can you test it once? Thanks! :))

**Comment by jelmervdl** [comment]
Yes, this has now been fixed!
```sh
$ cat test.txt | apertium-destxt | apertium -f none -u eu-es | apertium-retxt
words words Esta
words@words la documentación
```
