### ISSUE TITLE
Remove deprecated lextor code

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium#87]
I suggest removing the `apertium-lextor` code from the master branch. We should also clean up other dead code.

**Comment by ftyers** [comment]
Done in 843a418. We could also consider moving `apertium-lex-tools` into Apertium now and calling it `lextor`. I like the name :D

**Comment by TinoDidriksen** [comment]
Would prefer to further decouple tools, not couple them. lex-tools specific code should be moved from lttoolbox to lex-tools.

**Comment by ftyers** [comment]
In that case, we could rename `apertium-lex-tools` to just `apertium-lextor` I guess. I think I'm happy either way.
