### ISSUE TITLE
national-encoding

### ISSUE THREAD

**Issue by kartikm** [apertium/apertium#91]
Friendly lintian from Debian shows this.

W: apertium: national-encoding usr/share/apertium/interchunk.dtd
N:
N:    A file is not valid UTF-8.
N:
N:    Debian has used UTF-8 for many years. Support for national encodings is
N:    being phased out. This file probably appears to users in mangled
N:    characters (also called mojibake).
N:
N:    Packaging control files must be encoded in valid UTF-8.
N:
N:    Please convert the file to UTF-8 using iconv or a similar tool.
N:
N:    Severity: warning
N:
N:    Check: files/encoding

Also in following files:

W: apertium: national-encoding usr/share/apertium/postchunk.dtd
W: apertium-dev: national-encoding usr/include/apertium-3.6/apertium/file_morpho_stream.h
W: apertium-dev: national-encoding usr/include/apertium-3.6/apertium/hmm.h
W: apertium-dev: national-encoding usr/include/apertium-3.6/apertium/morpho_stream.h
W: apertium-dev: national-encoding usr/include/apertium-3.6/apertium/string_utils.h
W: apertium-dev: national-encoding usr/include/apertium-3.6/apertium/tagger_utils.h

Thanks.

**Comment by ftyers** [comment]
Closed in 642640a and 75b7fd3. Please reopen if you find some others :)

**Comment by kartikm** [comment]
Quick! Thanks!!
