### ISSUE TITLE
Problems with spaces in apertium-transfer -b

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium#96]
Today I updated lttoolbox and got (after solving a crash) a problem with a blank which I cannot solve. The problem is here:

```
$ echo "^Kortchnoï<np><cog><mf><sp>/Kortxnoi<np><cog><mf><sp>$ ^épouser<vblex><ifi><p3><sg>/casar# amb<vblex><pron><ifi><p3><sg>$" | apertium-transfer -b /home/hector/apertium/apertium-fra-cat/apertium-fra-cat.fra-cat.t1x /home/hector/apertium/apertium-fra-cat/fra-cat.t1x.bin
^Kortxnoi<np><cog><mf><sp>$ es<prn><pro><ref><p3><mf><sp>$^ ^anar<vaux><p3><sg>$ ^casar<vblex><inf># amb$
```

The problem is that I receive now 
`$ es<prn>`
instead of (as I previously received)
` $es<prn>`

The result is

> Kortxnoies va casar

instead of

> Kortxnoi es va casar

(as previously)

**Comment by khannatanmai** [comment]
Why is the output like this: ``es<prn><pro><ref><p3><mf><sp>$^``?

**Comment by hectoralos** [comment]
Right! This is an old bug, which for some reason used to work in the previous version. Thanks!
